### ISSUE TITLE
Creating fingerprints file based on folder followed by asterisk results in near empty file 12kB

### ISSUE THREAD

**Issue by slrslr** [jhnc/findimagedupes#17]
Debian 11 package Version: 2.18-7+b2

$ findimagedupes -f /dev/shm/fpdb-nonrecur-asteriskk-git -n -- "/a/b/_c d/e f/*"

produces 12kB file (no fingerprints?)

$ findimagedupes -f /dev/shm/fpdb-nonrecur-git -n -- "/a/b/_c d/e f/"

produces ~5MB file

isn't it unnecessarily confusing for the user?

**Comment by jhnc** [comment]
findimagedupes should have warned something like:
```
Warning: skipping file: /a/b/_c d/e f/*
```
Do you actually have a file or directory literally called `/a/b/_c d/e f/*` ?

I'm afraid POSIX shell syntax is what it is.
Glob wildcards (`*`, `?`, etc) only expand when not inside quotes.

Perhaps you intended something like: `"/a/b/_c d/e f/"*` ?
