### ISSUE TITLE
Use of uninitialized value in concatenation

### ISSUE THREAD

**Issue by ninalanyon** [jhnc/findimagedupes#22]
I haven't used findimagedupes for a while and today it did this:

$ findimagedupes --version
Use of uninitialized value in concatenation (.) or string at /usr/lib/x86_64-linux-gnu/perl5/5.34/findimagedupes/C.pm line 4.
Use of uninitialized value in concatenation (.) or string at /usr/lib/x86_64-linux-gnu/perl5/5.34/findimagedupes/C.pm line 4.
Use of uninitialized value $ENV{"LDFLAGS"} in string at /usr/lib/x86_64-linux-gnu/perl5/5.34/findimagedupes/C.pm line 4.
findimagedupes 2.19.1

I imagine there is something simple that is wrong but I don't know what.  I tried to see if my version of findimagedupes is out of date but I can't see the version number on the Github repository.

**Comment by jhnc** [comment]
Thanks for the report.

This is a bug with debian (and related distro) packaging.
See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023938

If I remember correctly, it is cosmetic and does not prevent the program running.

It should be fixed in more recent versions.

**Comment by jhnc** [comment]
(To see a particular version, switch to the relevant tag ( `git tag` from a private copy, or select from the dropdown of the "switch branch/tag" menu at https://github.com/jhnc/findimagedupes )

**Comment by jhnc** [comment]
If you can't update,  you can silence the warnings by setting the problematic variables.
Something like:
```
CFLAGS= CPPFLAGS= LDFLAGS= findimagedupes [...]

**Comment by ninalanyon** [comment]
Thank you!
